# Generated by Django 4.2.1 on 2023-06-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0003_alter_food_image_alter_personne_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="food_img"),
        ),
        migrations.AlterField(
            model_name="personne",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="user_img"),
        ),
    ]
