# Generated by Django 4.2.1 on 2023-06-04 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0009_alter_nutritional_diary_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritional_diary",
            name="slog",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personne",
            name="date_of_birth",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 4, 23, 14, 36, 551565, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
