# Generated by Django 4.2.1 on 2023-06-03 13:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="food")),
            ],
        ),
        migrations.CreateModel(
            name="Health_Problem",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Personne",
            fields=[
                (
                    "username",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=120)),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=120)),
                ("sex", models.CharField(max_length=10)),
                ("date_of_birth", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Nutritional_Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.datetime.now)),
                ("day_of_week", models.CharField(max_length=10)),
                (
                    "food",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="predict.food",
                    ),
                ),
                (
                    "health_pb",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="predict.health_problem",
                    ),
                ),
                (
                    "personne",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="predict.personne",
                    ),
                ),
            ],
        ),
    ]
