# Generated by Django 4.2.1 on 2023-06-04 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0010_nutritional_diary_slog_alter_personne_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutritional_diary",
            name="slog",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="personne",
            name="date_of_birth",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 4, 23, 33, 40, 837923, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
